language: ruby

services:
  - docker

before_install:
- docker build -t finn .
- mkdir ${HOME}/pg_data

- sudo service postgresql stop # wait for postgresql to shutdown: https://github.com/travis-ci/travis-ci/issues/4842#issuecomment-311527059
- while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
- docker run --name finn -v $(pwd):/home/finn -v ${HOME}/pg_data:/var/lib/postgresql -p 5432:5432 -p 8888:8888 -d -e EARTHDATAUSER -e EARTHDATAPW finn
- docker exec finn jupyter nbconvert --ExecutePreprocessor.timeout=600 --to notebook --execute /home/finn/work_testOTS_092018/main_testOTS_092018.ipynb
