language: ruby

services:
  - docker

before_install:
- docker build -t finn .
- mkdir ${HOME}/pg_data

script:
- docker run --name finn -v $(pwd):/home/finn -v ${HOME}/pg_data:/var/lib/postgresql -p 5432:5432 -p 8888:8888 -d -e EARTHDATAUSER=$EARTHDATAUSER -e EARTHDATAPW=$EARTHDATAPW finn
- docker exec finn jupyter nbconvert --ExecutePreprocessor.timeout=600 --to notebook --execute /home/finn/work_testOTS_092018/main_testOTS_092018.ipynb
